### ISSUE TITLE
Could not find function pbfBigIntUpdate(BIGINT, BIGINT, BIGINT) returns BIGINT

### ISSUE THREAD

**Issue by Tagar** [Peter-Ebert/impala-pbf-count#2]
I see `pbfBigIntUpdate` is int header and cc files .. not sure why it does not find it.
Perhaps needs to be compiled differently for bigint? 

![image](https://user-images.githubusercontent.com/3013418/59993559-ed362280-960d-11e9-9ab0-3e3022949928.png)

**Comment by Tagar** [comment]
It's actually not due to BigInt..

Getting similar error for CountInt

```
AnalysisException: Could not find function pbfIntUpdate(INT, BIGINT, BIGINT) returns BIGINT in: 

hdfs://epsdatalake/user/rdautkha/libpbfcount.so 

Check that function name, arguments, and return type are correct.

```

**Comment by Peter-Ebert** [comment]
Resolved by https://github.com/Peter-Ebert/impala-pbf-count/commit/b0c23a768f58d6057aa0a16dafc9d2f30a8b0510
It's dangerous to copy paste off the docs :)

**Comment by Tagar** [comment]
Thanks a lot !

That resolves .. will do some testing :-)
